# vim:ft=kitty

## name:     Color-E-Ink
## author:   Algilbert Gomez (https://github.com/alexxGmZ)
## forker:   Sandy X (https://github.com/sandyx86)
## license:  MIT
## upstream: https://github.com/sandyx86/color-e-ink.kitty/blob/main/E-Ink.conf
## blurb:    A theme aiming to imitate color e-ink displays.

foreground #474747
background #CCCCCC
selection_foreground none
selection_background #AEAEAE

cursor none

# black
color0  #CCCCCC
color8  #CCCCCC

# red
color1  #a54f52
color9  #a54f52

# green
color2  #649841
color10  #649841

# yellow
color3  #bc9b37
color11  #bc9b37

# blue
color4  #4f7cc3
color12  #4f7cc3

# magenta
color5  #8c69bd
color13  #8c69bd

# cyan
color6  #51a3a8
color14  #51a3a8

# black
color7  #575757
color15  #575757
